excluded_words:
  - cdda
  - dda
  - cata
  - Zets
  - overmap
  - Magiclysm
  - uncraft
  - Nocts
  - tefnut
  - evac
  - cyberjunkie
  - medikit
  - triffgus
  - wildy
  - D'ya
  - bfg
  - omnicam
  - attunements
  - technomancer
  - factionless
  - npc
  - npcs
  - tshirt
  - bommers
  - veh
  - Dinomod
  - Nechronica
  - IchBinNexus
  - PoraComp
  - Pharm
  - Porawep
  - Touhou
