excluded_words:
  - Alpen
  - Chia
  - Choco
  - D'ya
  - Dinomod
  - FictonalWeapons
  - Frosties
  - Frusli
  - IchBinNexus
  - Jordans
  - KantoJolto
  - Krave
  - Lizis
  - Magiclysm
  - Mcvitie
  - Moma
  - Nechronica
  - Nesquik
  - Nocts
  - Oatibix
  - Oomf
  - Pharm
  - PoraComp
  - Porawep
  - Rais
  - Superseeded
  - Touhou
  - Weetabix
  - Wkk
  - Zets
  - attunements
  - bads
  - bfg
  - bommers
  - boxs
  - brandcerealmod
  - cata
  - cbm
  - cbms
  - cdda
  - chilidogs
  - colamdew
  - crispycran
  - cyberjunkie
  - dayquil
  - dda
  - ecig
  - evac
  - eyebot
  - factionless
  - fchicken
  - fic
  - ficmags
  - foon
  - grahmcrackers
  - halligan
  - jihelucake
  - jrr
  - kelloggs
  - kompot
  - lutefisk
  - mbag
  - medikit
  - nachosc
  - nachosm
  - nachosmc
  - neccowafers
  - necronimicron
  - npc
  - npcs
  - oatie
  - omnicam
  - orjson
  - overmap
  - picklocks
  - quikclot
  - reformatter
  - rrr
  - shutil
  - slingpack
  - sloppyjoe
  - spezi
  - ssWWWWWWWWssssssssssssss
  - tazer
  - technomancer
  - tefnut
  - teleumbrella
  - toastem
  - toasterpastryfrozen
  - triffgus
  - tshirt
  - tttt
  - ttttt
  - uncraft
  - vacutainer
  - veggy
  - veh
  - vitA
  - vitC
  - wildy
  - xacto
  - xanax
